name: nextdeck
description: Nextcloud Deck Client (Flutter, Cupertino)
publish_to: 'none'
version: 1.6.0+0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  flutter_markdown: ^0.7.3+1
  share_plus: ^10.0.2
  url_launcher: ^6.3.0
  file_picker: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/icon.png
